version: '2'

services:

  redis:
    image: redis
    container_name: "redis"

  chat:
    image: tomfernandez/redis_chat
    container_name: "chat"
    ports:
      - "8080:8080"
    environment:
      SOCKET_URL: 192.168.99.100
      SOCKET_PORT: 8082
      REDIS_URL: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  chat_1:
    image: tomfernandez/redis_chat
    container_name: "chat_1"
    ports:
      - "8081:8080"
    environment:
      SOCKET_URL: 192.168.99.100
      SOCKET_PORT: 8081
      REDIS_URL: redis
      REDIS_PORT: 6379
    depends_on:
      - redis


networks:
  default:
    external:
      name: chat_network