version: '2'

services:

  redis:
    image: redis

  chat:
    image: chat
    container_name: "chat"
    build:
      context: .
      dockerfile: Dockerfile.chat
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file: env

networks:
  default:
    external:
      name: chat_network